[package]
name = "domain-to-ip"
version = "0.1.0"
authors = ["Name <you@example.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
trust-dns-resolver = "*"